x1 = int(input("Digite o valor de x1: "))
y1 = int(input("Digite o valor de y1: "))
x2 = int(input("Digite o valor de x2: "))
y2 = int(input("Digite o valor de y2: "))
d = (((x2- x1)**2) + ((y2-y1)**2))**(1/2)
print("A distância entre o ponto P(x1,y1) e o ponto P(x2,y2) é: ", d)